version: "3"
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-4.4-latest
    environment:
      - DB_SERVER_HOST=192.168.43.61
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    ports:
      - 10051:10051
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /u01/zabbix/zabbix-server:/data
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-4.4-latest
    environment:
      - DB_SERVER_HOST=192.168.43.61
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - PHP_TZ="Asia/Shanghai"
    ports:
      - 28808:80
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - /u01/zabbix/fonts/simkai.ttf:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf
      - /u01/zabbix/zabbix-web:/data
    depends_on:
      - zabbix-server

